name: manage-azure-policy-73d736c9
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Auditing_on_SQL_server_should_be_enabled_a6fb4358-5bf4-4ad7-ba82-2cd2f41ce5e9/**'
#      - .github/workflows/manage-azure-policy-73d736c9.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_73d736c9}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Auditing_on_SQL_server_should_be_enabled_a6fb4358-5bf4-4ad7-ba82-2cd2f41ce5e9/**
