name: manage-azure-policy-d60106ae
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/System_updates_should_be_installed_on_your_machines_86b3d65f-7626-441e-b690-81a8b71cff60/**'
#      - .github/workflows/manage-azure-policy-d60106ae.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d60106ae}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/System_updates_should_be_installed_on_your_machines_86b3d65f-7626-441e-b690-81a8b71cff60/**
