name: manage-azure-policy-ee20f5fe
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Vulnerabilities_on_your_SQL_databases_should_be_remediated_feedbf84-6b99-488c-acc2-71c829aa5ffc/**'
#      - .github/workflows/manage-azure-policy-ee20f5fe.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ee20f5fe}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Vulnerabilities_on_your_SQL_databases_should_be_remediated_feedbf84-6b99-488c-acc2-71c829aa5ffc/**
