name: manage-azure-policy-ff2ca266
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Disk_encryption_should_be_applied_on_virtual_machines_0961003e-5a0a-4549-abde-af6a37f2724d/**'
#      - .github/workflows/manage-azure-policy-ff2ca266.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ff2ca266}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Disk_encryption_should_be_applied_on_virtual_machines_0961003e-5a0a-4549-abde-af6a37f2724d/**
