name: manage-azure-policy-c4809e90
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Monitor_missing_Endpoint_Protection_in_Azure_Security_Center_af6cd1bd-1635-48cb-bde7-5b15693900b9/**'
#      - .github/workflows/manage-azure-policy-c4809e90.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_c4809e90}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Monitor_missing_Endpoint_Protection_in_Azure_Security_Center_af6cd1bd-1635-48cb-bde7-5b15693900b9/**
