name: manage-azure-policy-852f53e8
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/MFA_should_be_enabled_accounts_with_write_permissions_on_your_subscription_9297c21d-2ed6-4474-b48f-163f75654ce3/**'
#      - .github/workflows/manage-azure-policy-852f53e8.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_852f53e8}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/MFA_should_be_enabled_accounts_with_write_permissions_on_your_subscription_9297c21d-2ed6-4474-b48f-163f75654ce3/**
