name: manage-azure-policy-83fb385b
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Service_Fabric_clusters_should_have_the_ClusterProtectionLevel_property_set_to_EncryptAndSign_617c02be-7f02-4efd-8836-3180d47b6c68/**'
#      - .github/workflows/manage-azure-policy-83fb385b.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_83fb385b}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Service_Fabric_clusters_should_have_the_ClusterProtectionLevel_property_set_to_EncryptAndSign_617c02be-7f02-4efd-8836-3180d47b6c68/**
