name: manage-azure-policy-c24ef942
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Vulnerabilities_should_be_remediated_by_a_Vulnerability_Assessment_solution_760a85ff-6162-42b3-8d70-698e268f648c/**'
#      - .github/workflows/manage-azure-policy-c24ef942.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_c24ef942}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Vulnerabilities_should_be_remediated_by_a_Vulnerability_Assessment_solution_760a85ff-6162-42b3-8d70-698e268f648c/**
